OWASP/RiskAssessmentFramework

web_deface/cache.py, web_deface/crawler.py, web_deface/deface_utils.py, web_deface/hash_gen.py, web_deface/monitor.py, web_deface/web_deface.py
@adeyosemanputra As asked to do, I have created the PR for remote web deface detection here instead.
**Before running:**
1. `pip install tqdm`
As there was no starting script for the repo, web deface can be run by navigating to `/web_deface` and running `python3 web_deface.py`.
**Development Environment**
```env
Ubuntu 18.04 LTS
Sublime Text 3
```
=> Add remote web deface detection

web_deface/README.md
Documentation for notification mediums used in web-deface detection.
They are:
- Twitter
- Slack
- Telegram
- Twilio SMS
The documentation contains:
- Procedure for insalling
- Arguments
- Tokens & their usage
**Checklist**
=> Add notification documentation

web_deface/notifs/telegram.py
Fix `common` bug/error in telegram notification medium.
**Development Environment**
```env
Ubuntu 18.04 LTS
Sublime Text 3
```
=> Fix `common` error

gui/README.md, gui/src/app/app-routing.module.ts, gui/src/app/app.component.css, gui/src/app/app.component.html, gui/src/app/material.module.ts, gui/src/app/view/profile/profile.component.css, gui/src/app/view/profile/profile.component.html, gui/src/app/view/profile/profile.component.ts, gui/src/app/view/resources/resources.component.css, gui/src/app/view/resources/resources.component.ts, gui/src/app/view/settings/settings.component.html, gui/src/app/view/support/support.component.css, gui/src/app/view/support/support.component.html, gui/src/app/view/support/support.component.ts, gui/src/styles.css
Implemented the support page and the profile page for the dashboard, Support from FAQ which links to [OWASP Application Security FAQ](https://www.owasp.org/index.php/OWASP_Application_Security_FAQ) and  other related sources which were found on the official [Owasp website](owasp.org)
- []   SideNav Avatar 
- []   Settings Page
- []   Home Page
- []   Tools Page
- []   Tools Page
- []   Other issue fixing
* Profile Section of the Dashboard
* Support Section of the Dashboard
* App routing
* Top ToolBar
* App component
* Global Styles
* Material Module
Run `ng serve` for a dev server. Navigate to …
=> Updated Profile And Support Page

gui/README.md, gui/src/app/app.component.css, gui/src/app/app.component.html, gui/src/app/view/profile/profile.component.css, gui/src/app/view/settings/settings.component.css, gui/src/app/view/settings/settings.component.html, gui/src/styles.css
Implemented the Settings page and fixed issues in profile page for the dashboard.
- [] Home Page
- [] History Page
- [] Tools Page
- [] Improvements in Settings
- [] Improvements in Profile
- [] Other issue fixing related to theme
* Profile Component
* SideNav Avatar
* Settings Component
* Top ToolBar
* Settings Page
* App component
* Global Styles
Run `ng generate component component-name` to generate a new component. You can also use `ng generate …
=> Added the Settings Page and fixed issues in Profile, Sidenav

gui/README.md, gui/package-lock.json, gui/package.json, gui/src/app/app.module.ts, gui/src/app/view/home/home.component.css, gui/src/app/view/home/home.component.html, gui/src/app/view/home/home.component.ts
Implemented the Home page and added the charts for risk assessment presentation for the dashboard.
- [] History Page
- [] Tools Page
- [] Improvements in Settings
- [] Improvements in Profile
- [] Other issue fixing related to theme
* Home Component
* Readme
Run `ng build` to build the project. The build …
=> Home Page with Charts

gui/README.md, gui/src/app/app-routing.module.ts, gui/src/app/app.module.ts, gui/src/app/material.module.ts, gui/src/app/view/history/history.component.css, gui/src/app/view/history/history.component.html, gui/src/app/view/history/history.component.ts, gui/src/app/view/tools/tools.component.css, gui/src/app/view/tools/tools.component.html, gui/src/app/view/tools/top10/top10.component.css, gui/src/app/view/tools/top10/top10.component.html, gui/src/app/view/tools/top10/top10.component.spec.ts, gui/src/app/view/tools/top10/top10.component.ts
Implemented the Tool page and added a chart onto the history page.
- [] History Page
- [] Upload Code
- [] Improvements in Settings
- [] Improvements in Profile
- [] Other issue fixing related to theme
* Tool Component
* History Component
* Material Module
* Readme
Run `ng build` to build the project. The …
=> partially developed Tools Component and Initialized History Component

gui/README.md, gui/src/app/material.module.ts, gui/src/app/view/history/history.component.css, gui/src/app/view/history/history.component.html, gui/src/app/view/history/history.component.ts
Added Charts to the History Page and Added table for downloading reports.
- [] Report Table Dynamic Fetching
- [] Upload Code
- [] Improvements in Settings
- [] Improvements in Profile
- [] Other issue fixing related to theme
* Tool Component
* Material Module
* Readme
Run `ng build` to build the project. The …
=> Added more charts and table to History Component

gui/src/app/app-routing.module.ts, gui/src/app/app.module.ts, gui/src/app/auth/auth-data.model.ts, gui/src/app/auth/auth.service.spec.ts, gui/src/app/auth/auth.service.ts, gui/src/app/auth/login/login.component.ts, gui/src/app/auth/user.model.ts, gui/src/app/view/history/history.component.ts
Added initial Authentication for the dashboard.
- Report Table Dynamic Fetching
- Upload Code
- Improvements in Authentication
- Auth Guard
* Login Component
* app routing Module
* User Model
* app Module
* History Module
* Readme
Run `ng generate component component-name` to generate a new component. You can also use `ng generate …
=> Initial Authentication For Dashboard

gui/README.md, gui/package-lock.json, gui/package.json, gui/src/app/app-routing.module.ts, gui/src/app/app.component.html, gui/src/app/app.component.ts, gui/src/app/app.module.ts, gui/src/app/auth/auth.service.ts, gui/src/app/auth/login/login.component.html, gui/src/app/auth/login/login.component.ts, gui/src/app/material.module.ts, gui/src/app/view/navigation/navigation.component.css, gui/src/app/view/navigation/navigation.component.html, gui/src/app/view/navigation/navigation.component.spec.ts, gui/src/app/view/navigation/navigation.component.ts, gui/src/app/view/resources/dialog-component/dialog-component.component.html, gui/src/app/view/resources/dialog-component/dialog-component.component.spec.ts, gui/src/app/view/resources/dialog-component/dialog-component.component.ts, gui/src/app/view/resources/resources.component.css, gui/src/app/view/resources/resources.component.html, gui/src/app/view/resources/resources.component.ts, gui/src/index.html
Redesign of the resource component with dialog popup.
- Upload Code
- Improvements in Authentication
- Auth Guard
* app routing Module
* login Component
* User Model
* Navigation Component
* app Module
* dialog Component
* auth Services
* Resource Component
* Readme
Run `ng generate component component-name` to generate a new …
=> Redesigning of the Resource Component And Addition of Auth Service

gui/README.md, gui/src/app/app-routing.module.ts, gui/src/app/view/home/home.component.html, gui/src/app/view/register/register.component.html, gui/src/app/view/register/register.component.spec.ts, gui/src/app/view/register/register.component.ts, gui/src/app/view/resources/resources.component.html, gui/src/app/view/resources/resources.component.ts
Adding of SANS TOP 25 to the resource page and fixing issues related to routing and auth guard
- Upload Code
- Improvements in Resources
- Auth Guard
* app routing Module
* login Component
* User Model
* Navigation Component
* app Module
* dialog Component
* auth Services
* Resource Component
* Readme
Run `ng generate …
=> Added SANS TOP 25 to the resources 

gui/README.md, gui/package-lock.json, gui/package.json, gui/src/app/app.component.ts, gui/src/app/app.module.ts, gui/src/app/view/tools/top10/top10.component.css, gui/src/app/view/tools/top10/top10.component.html, gui/src/app/view/tools/top10/top10.component.ts, gui/src/tsconfig.app.json
Adding the upload feature to OWASP top 10 test. using vaadin upload component
* tsconfig
Run `ng build` to …
=> Drag and Drop Code Upload and URL input for repository

api/.gitignore, api/package-lock.json, api/package.json, api/readme.md, api/src/database/mongo.js, api/src/database/users.js, api/src/index.js
Initial Development of the API with endpoints using in memory database of mongodb.
-   Create Schemas for USER
-   File Upload Endpoint
-   Test Result Endpoint
-   Authentication
-   User Registration
-   Report Generation
-   User Details Endpoint
-   Source
-   Package.json
-   index.js
-   Database component
**Risk Assessment Framework API**
----
*GET USERS*
* **URL**
http://localhost:3000/
* **Method:**
`GET`
*  **URL Params**
No Params 
**Required:**
No Required fields
**Optional:**
No Optional fields
* **Data Params**
No Data Params
* **Success Response:**
* **Code:** 200 <br />
**Content:** `[
{
"_id": "xxxxxxxxxxxxxxx",
"title": "Hello, now from the in-memory database!"
}
]`
* **Sample Call:**
curl …
=> Initial Development of the API

api/package-lock.json, api/package.json, api/readme.md, api/sonar-project.properties, api/src/index.js, api/src/sonarqube/callAPI.js
scan project endpoint to scan the code using sonarqube scanner.
-   Create Schemas for USER
-   Test Result Endpoint
-   Authentication
-   User Registration
-   Report Generation
-   User Details Endpoint
-   Source
-   sonarqube
-   callAPI.js
-   Package.json
-   index.js
**Risk Assessment Framework API**
----
*POST CODE*
* **URL**
<http://localhost:3000/upload/code>
* **Method:**
`POST`
*  **URL Params**
No Params 
**Required:**
code field of type file
**Optional:**
No Optional fields
* **Data Params**
`code` param of `File` Type 
* **Success Response:**
* **Code:** 200 <br />
**Content:** `[
File is uploaded
]`
* **Sample Call:**
$ curl -F ‘data=@path/to/local/file’ UPLOAD_ADDRESS
*GET USERS*
* **URL** …
=> Adding the SCAN project endpoint to scan the project using sonarqube

api/.gitignore, api/.scannerwork/report-task.txt, api/config/database.js, api/package-lock.json, api/package.json, api/readme.md, api/routes/projects.js, api/routes/users.js, api/sonar-project.properties, api/src/app/api/controllers/projects.js, api/src/app/api/controllers/users.js, api/src/app/api/models/projects.js, api/src/app/api/models/users.js, api/src/index.js, api/src/sonarqube/callAPI.js
Adding the authentication and routing with mongodb connection to a cluster hosted.
-   Report Generation
-   Source
-   Routes
-   Config
-   Package.json
-   index.js
**Risk Assessment Framework API**
----
*POST CODE*
* **URL**
<http://localhost:3000/upload/code>
* **Method:**
`POST`
*  **URL Params**
No Params 
**Required:**
code field of type file
**Optional:**
No Optional fields
* **Data Params**
`code` param of `File` Type 
* **Success Response:**
* **Code:** 200 <br />
**Content:** `[
File is uploaded
]`
* **Sample Call:**
$ curl -F ‘data=@path/to/local/file’ UPLOAD_ADDRESS
*SCAN*
* **URL**
http://localhost:3000/scan/:id
* **Method:**
`GET`
*  **URL Params**
[id]
**Required:**
[id]
**Optional:**
No …
=> Authentication and MongoDB Atlas connection

api/.dockerignore, api/DOCKERFILE, api/routes/users.js, api/src/app/api/controllers/users.js, api/src/index.js, gui/src/app/view/tools/top10/top10.component.html
Connecting the upload file to the api
* tsconfig
Run `ng build` to build the project. The build artifacts …
=> upload file back-end connection

gui/README.md, gui/src/app/models/project.model.ts, gui/src/app/shared/rest-api.service.ts, gui/src/app/view/history/history.component.ts
Connecting the History component charts with the rest-api service
* tsconfig
Run `ng build` to build the …
=> chart data populating from the rest api

api/routes/projects.js, api/src/app/api/controllers/projects.js, api/src/index.js, gui/README.md, gui/src/app/app-routing.module.ts, gui/src/app/app.module.ts, gui/src/app/material.module.ts, gui/src/app/shared/rest-api.service.ts, gui/src/app/view/resources/resources.component.html, gui/src/app/view/tools/top10/bottom-sheet-overview-example-sheet.html, gui/src/app/view/tools/top10/top10.component.css, gui/src/app/view/tools/top10/top10.component.html, gui/src/app/view/tools/top10/top10.component.ts
Creating A Bottom sheet to perform scan and process the response from the rest api and triggering sonar-qube scan.
* Material module Component
* rest-api-service Component
* tsconfig
Run `ng generate component component-name` to generate a new component. You can also …
=> create project and perform scan / Bottom sheet with options

api/src/index.js, api/src/sonarqube/callAPI.js, gui/README.md, gui/src/app/app.module.ts, gui/src/app/material.module.ts, gui/src/app/shared/rest-api.service.ts, gui/src/app/view/history/history.component.ts, gui/src/app/view/tools/top10/bottom-sheet-overview-example-sheet.html, gui/src/app/view/tools/top10/top10.component.ts
Dialog to display results of the scanned project.
* Material module Component
* rest-api-service Component
* tsconfig
Run `ng generate component component-name` to generate a new component. You can also use `ng generate …
=> Added the result dialog after scan complete

api/.gitignore, api/.scannerwork/report-task.txt, api/.vscode/settings.json, api/sonar-project.properties, api/src/index.js, api/src/sonarqube/callAPI.js, gui/src/app/app-routing.module.ts, gui/src/app/view/history/charts/charts.component.ts, gui/src/app/view/history/history.component.ts, gui/src/app/view/profile/profile.component.ts, gui/src/app/view/tools/top10/analysis-report/analysis-report.component.css, gui/src/app/view/tools/top10/analysis-report/analysis-report.component.html, gui/src/app/view/tools/top10/analysis-report/analysis-report.component.ts, gui/src/app/view/tools/top10/bottom-sheet-overview-example-sheet.html, gui/src/app/view/tools/top10/top10.component.ts
Updated gui in analysis-report component
* Material module Component
* rest-api-service Component
* tsconfig
Run `ng build` to build the …
=> Updated analysis-report
